export const errorCodes = {
	ERR_EMAIL_IN_USE: 'ERR_EMAIL_IN_USE',
	ERR_USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',
	ERR_LOGIN_FAILED: 'ERR_LOGIN_FAILED',
	ERR_UNAUTHORIZED: 'ERR_UNAUTHORIZED',
	ERR_FORBIDDEN: 'ERR_FORBIDDEN',
	ERR_ADVENTURE_NOT_FOUND: 'ERR_ADVENTURE_NOT_FOUND',
	ERR_CHAPTER_NOT_FOUND: 'ERR_CHAPTER_NOT_FOUND',
};

export const errorMessages = {
	BAD_REQUEST: 'Bad request',
	UNAUTHORIZED: 'Unauthorized',
	FORBIDDEN: 'Forbidden',
	NOT_FOUND: 'Requested resource not found',
};
